version: 2

models:
  - name: stg_users
    columns:
      - name: user_id
        tests: [unique, not_null]
  - name: stg_notifications_sent
    columns:
      - name: notification_id
        tests: [unique, not_null]
      - name: user_id
        tests: [not_null]
  - name: stg_notification_events
    columns:
      - name: event_id
        tests: [unique, not_null]
      - name: notification_id
        tests: [not_null]
  - name: stg_unsubscribes
    columns:
      - name: user_id
        tests: [not_null]